Fix #2088 - Add VPN promo banner
mozilla/blurts-server pull request #2089
Opened 2021-04-07 03:03 UTC by maxxcrawford

## Summary

Add VPN promo banner across the website

TODO: 
- Add l10n Strings
- Add language gate
- Hide by default
- Add UTMs/URLs
- Native Browser Test
- Confirm collision test with survey

## Testing

- Go to https://monitor-v2.herokuapp.com/ 
- Click link
  - Expected: Goes to https://www.mozilla.org/en-US/products/vpn/

2021-04-07 14:15 UTC, groovecoder commented on public/css/vpn-promo-banner.css
> +
needs css lint fixes.

2021-04-07 19:17 UTC, maxxcrawford commented on public/css/vpn-promo-banner.css
> +
🧹

2021-04-08 14:24 UTC, groovecoder requested changes

2021-04-08 21:09 UTC, groovecoder commented
Oops, needs conflict resolution.

2021-04-09 15:35 UTC, merged