Mntor 983 settings v2 frontend
mozilla/blurts-server pull request #2763
Opened 2023-01-13 01:44 UTC by rhelmer

This covers the following issues:

- migrate email to new platform MNTOR-1057
- frontend work for v2 settings MNTOR-983

It depends on the backend changes in https://github.com/mozilla/blurts-server/pull/2743

2023-01-13 05:37 UTC, rhelmer commented
@flozia a few things are missing in V2 that we need to implement this, that aren't explicitly covered in figma:

- error messages
  - we can either redirect to an error page (which is what V1 does), or we can show some kind of error message using JS: 
![image](https://user-images.githubusercontent.com/61412/212245088-550240c6-2c19-4348-aaee-4e32c25f9e6a.png)
  - see [src/client/js/settings.js](https://github.com/mozilla/blurts-server/pull/2763/files#diff-790e0d9a5e177ba94933197ab52bc546ed75f9a5026f8e306572cc0b02dc3a0c) for where the client is `fetch`ing the API (and not handling the exceptions right now just logging them to the console)
- success messages
  - I didn't find this in figma, but I see that V1 (current production on monitor.firefox.com) shows this using JS: 
![image](https://user-images.githubusercontent.com/61412/212244604-5f222494-79c6-4231-a9d8-0d70ffcf5773.png)
- image formats
  - I exported the images in use here from Figma using PNG, is SVG preferred?

2023-01-13 08:47 UTC, flodolo requested changes
See the linter results https://github.com/mozilla/blurts-server/pull/2763/checks

More important: what's the reasoning behind splitting these strings into a separate file? This will require retranslating them across all locales.

If we do this, we should relook at the IDs that we used, and use better ones (providing more context on how/where the string is used).

2023-01-13 08:47 UTC, flodolo commented on locales/en/settings.ftl
> +email-address-limit = Your account includes monitoring of up to { $limit } emails
This should use the plural structure (like the first string in this file)

2023-01-13 18:50 UTC, toufali commented
> what's the reasoning behind splitting these strings into a separate file?

Hi @flodolo – as part of this Refresh release, we're re-architecting/refactoring.  The strings @rhelmer moved over are specific only to the settings page, and we have been creating a new .ftl for each page in the site (~5 total expected for Refresh).

The app.ftl file has become very large and hard to navigate – We're hoping to reserve this page for site-wide strings only. I was under the impression that .ftl files concat and that moving strings between files was ok, but it sounds like I was wrong!  

For this case is it ok to separate into a more logical file structure?  Monitor is expected to continue growing, and I'd like to set up good practice in the Refresh release, so future features can benefit.

2023-01-13 19:00 UTC, flodolo commented
> The app.ftl file has become very large and hard to navigate – We're hoping to reserve this page for site-wide strings only. I was under the impression that .ftl files concat and that moving strings between files was ok, but it sounds like I was wrong!

No concatenation ;-) 
https://pontoon.mozilla.org/it/firefox-monitor-website/

I'm OK with splitting things up in smaller files, as long as it's done purposefully. Pontoon will show a match in translation memory, so it doesn't need to be translated from scratch. But we should also take the opportunity to do a better job with IDs, since we're basically creating new strings.

I'm heading offline for the week, but I'll try to provide more comments in the next days of what I mean.

2023-01-16 17:03 UTC, flodolo commented on locales/en/settings.ftl
> +resend-verification = Resend verification email
I understand these come from existing strings, but we didn't do a good job here, and we can use this work to improve things.

IDs should provide context for localizers, if there's no comment doing it. For example: is this a button, a link, something else? Putting more information, and using a more specific ID based on the context would help localizers, and discourage reuse in different contexts.

In this case I would go with `settings-resend-verification-link`.

This applies to all the strings in this file, in particular to very undescriptive ones like `menu`.
`email-verification-required`: is it a title, a message? These might require different style in different locales.

2023-01-16 20:27 UTC, pdehaan commented on src/client/js/settings.js
> +    addEmailDialogContent.textContent = `Verify the link sent to ${email} to add it to Firefox Monitor. Manage all email addresses in Settings.`
Q: Does this need to be localized?

2023-01-16 20:27 UTC, pdehaan commented on src/utils/email.test.js
> +import EmailUtils from './email'
Should these have .js extensions for consistency?

2023-01-16 20:27 UTC, pdehaan commented on src/views/email-2022.js
> +  if (!(data.whichPartial === 'email_partials/email-monthly-unresolved')) {
Why not this?
```suggestion
  if (data.whichPartial !== 'email_partials/email-monthly-unresolved') {
```

2023-01-16 20:27 UTC, pdehaan commented on src/views/partials/settings.js
> +      <h3>Breach alert preferences</h3>
Q: Localized?

2023-01-16 20:27 UTC, pdehaan commented on src/views/partials/settings.js
> +      <div>${getMessage('deactivate-account')}.</div>
Q: Should the period be within the translated string?

2023-01-17 05:52 UTC, flodolo commented on locales/en/settings.ftl
> +add-another-email = Add a new email address to see if it's been involved in a breach
https://github.com/mozilla/blurts-server/pull/2763/checks

2023-01-17 05:53 UTC, flodolo commented on locales/en/settings.ftl
> +deactivate-account = You can deactivate Firefox Monitor by deleting your Firefox account
Indeed, both Firefox Monitor and Firefox account should use the corresponding term.

2023-01-17 16:23 UTC, rhelmer commented on src/client/js/settings.js
> +    if (!response || !response.ok) {
This is from the existing front-end code, but I agree it doesn't make much sense as-is right now, will correct this.

2023-01-17 16:56 UTC, rhelmer commented
This is still a draft PR, let's move this work over to https://github.com/mozilla/blurts-server/pull/2765 instead.

2023-01-17 16:56 UTC, closed without merging