Fix MNTOR-1795 - Add ADR for L10N workflow updates
mozilla/blurts-server pull request #3097
Opened 2023-06-02 14:18 UTC by maxxcrawford

2023-06-09 20:56 UTC, maxxcrawford commented on docs/adr/0006-localization-workflow.md
> +* Status: proposed
Update status once approved

2023-06-12 09:02 UTC, flodolo requested changes

2023-06-13 19:23 UTC, maxxcrawford commented on docs/adr/0006-localization-workflow.md
> +* Good, localizers workflow, new strings will trigger localization review requests via CODEOWNERS.
Removed in 13e494d2a9ff8c05f30ace880a3dbe5256d46e0d

2023-06-13 19:23 UTC, maxxcrawford commented on docs/adr/0006-localization-workflow.md
> +* With the React refactor, this is a good time to revisit our processes, and determine what makes the most since
Rewritten in 13e494d2a9ff8c05f30ace880a3dbe5256d46e0d

> With the React refactor, this is a good time to revisit our processes, and determine what works the best for everyone.

2023-06-14 04:58 UTC, rhelmer approved these changes
lgtm, flod is the expert here so I'll defer to him. Thanks for writing this up!

2023-06-14 04:58 UTC, rhelmer commented on docs/adr/0006-localization-workflow.md
> +  * This is also a chance to better align with other Mozilla projects
```suggestion
  * This is also a chance to better align with other Mozilla projects.
```

2023-06-14 06:15 UTC, flodolo approved these changes
Fixed some of the nits I reported in a separate commit, hope that's OK.

2023-06-14 06:15 UTC, flodolo commented on docs/adr/0006-localization-workflow.md
> +* Seperate Repo / Automated Syncing
All the other `seperate` typos are still around.

2023-07-11 14:52 UTC, merged