MNTOR-1812 Add filter component in exposures area
mozilla/blurts-server pull request #3189
Opened 2023-07-05 20:38 UTC by codemist

# References: 
Jira: MNTOR-
Figma: 

# Description

# Screenshot (if applicable)

Not applicable.

# How to test

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2023-07-05 23:31 UTC, pdehaan commented on src/app/(proper_react)/Dashboard.tsx
> +import { FilterIcon, QuestionMarkCircle } from "../components/server/Icons";
```sh
./src/app/(proper_react)/Dashboard.tsx
14:10  Warning: 'FilterIcon' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
14:22  Warning: 'QuestionMarkCircle' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
```

2023-07-05 23:31 UTC, pdehaan commented on src/app/(proper_react)/Dashboard.tsx
> +  const [isFilterPopupOpen, setIsFilterPopupOpen] = useState(false);
```sh
./src/app/(proper_react)/Dashboard.tsx
28:10  Warning: 'isFilterPopupOpen' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
28:29  Warning: 'setIsFilterPopupOpen' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
```

2023-07-05 23:31 UTC, pdehaan commented on src/app/(proper_react)/Dashboard.tsx
> +  const showModalContentExposureType = () => {
```sh
./src/app/(proper_react)/Dashboard.tsx
36:9  Warning: 'showModalContentExposureType' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
```

2023-07-05 23:31 UTC, pdehaan commented on src/app/(proper_react)/Dashboard.tsx
> +  const showModalContentStatus = () => {
```sh
./src/app/(proper_react)/Dashboard.tsx
42:9  Warning: 'showModalContentStatus' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
```

2023-07-06 00:37 UTC, pdehaan commented on src/app/(proper_react)/ExposuresFilter.tsx
> +  const [isFilterPopupOpen, setIsFilterPopupOpen] = useState(false);
```sh
./src/app/(proper_react)/ExposuresFilter.tsx
16:10  Warning: 'isFilterPopupOpen' is assigned a value but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
```

2023-07-06 05:14 UTC, flodolo commented on locales-pending/premium.ftl
> +  In both cases, Removals typically take 7-14 days. Some can take longer, while others can happen within the hour.
I would split them at the new line.

2023-07-06 05:17 UTC, flodolo requested changes

2023-07-06 05:17 UTC, flodolo commented on locales-pending/premium.ftl
> +modal-exposure-type-description = We search for you in all known data breaches and { $data_broker_sites_total_num } data broker sites that sell your personal info. Here are the two types of exposures
Make this a plural string.

2023-07-06 05:17 UTC, flodolo commented on locales-pending/premium.ftl
> +modal-exposure-status-description = We search for exposures in all known data breaches and { $data_broker_sites_total_num } data broker sites that sell your personal info.
Make this a plural string anyway.

Also: "it will always be plural" -> "it will always be more than 1".

2023-07-06 05:17 UTC, flodolo commented on locales-pending/premium.ftl
> +modal-exposure-status-fixed = <b>Fixed</b> means the exposure has been resolved and theres no action for you to take.
```suggestion
modal-exposure-status-fixed = <b>Fixed</b> means the exposure has been resolved and there’s no action for you to take.
```

2023-07-11 15:04 UTC, closed without merging