MNTOR-1681 and MNTOR-1678 - Inject scanned results into dashboard & exposure cards
mozilla/blurts-server pull request #3234
Opened 2023-07-19 18:08 UTC by codemist

# References: 
Jira: MNTOR-1681 and MNTOR-1678
Figma: https://www.figma.com/file/CaEKIhvSJqf6KNIMzSkt40/Concepts-for-Monitor-MVP-Redesign?type=design&node-id=1205-51843&mode=design&t=VZy8sVkixi8S0wEK-4

# Description
This utilizes the scanned results data into the `ExposureCard` element. 

# Screenshot (if applicable)
<img width="1197" alt="image" src="https://github.com/mozilla/blurts-server/assets/13066134/29bb0c97-7961-4954-98d5-0112cfd8f4cb">

# How to test

After running a scan on `/redesign/user/welcome/`, the dashboard should be populated with mocked "Info for sale" type exposure cards representing data brokers, alongside pre-existing data breach cards.

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2023-07-19 18:50 UTC, pdehaan commented on src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
> +              statusPillType={"needAction"}
```suggestion
              statusPillType="needAction"
```

2023-07-19 18:50 UTC, pdehaan commented on src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
> +                statusPillType={"needAction"}
```suggestion
                statusPillType="needAction"
```

2023-07-19 18:50 UTC, pdehaan commented on src/app/(proper_react)/redesign/(authenticated)/user/dashboard/View.tsx
> +                statusPillType={"needAction"}
```suggestion
                statusPillType="needAction"
```

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          exposureCategoryLabel="Family members"
Q: Does this label need to be localized? (not sure if it's user facing)

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          exposureCategoryLabel="Phone Number"
Same Q as above, re: l10n

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          exposureCategoryLabel="Email"
Same Q as above, re: l10n

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          exposureCategoryLabel="Address"
Same Q as above, re: l10n

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          exposureCategoryLabel="Other"
Same Q as above, re: l10n

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +          num={exposureItem.emails.length} // Use emails.length instead of phones.length
nit: not sure if we need the comment.

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +            icon={<PhoneIcon alt="" width="13" height="13" />} // todo: add password icon
```suggestion
            icon={<PhoneIcon alt="" width="13" height="13" />}
```

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +            icon={<QuestionMarkCircle alt="" width="13" height="13" />} // todo: add password icon
```suggestion
            icon={<QuestionMarkCircle alt="" width="13" height="13" />}
```

2023-07-19 18:50 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +}
nit: not sure how well this will localize (unless we only care about en-us, but still worth pointing out maybe)

2023-07-19 18:50 UTC, pdehaan commented on src/db/tables/onerep_scans.ts
> +export interface GetLatestOnerepScanResult {
nit: I think this is the only interface prefixed w/ `Get`, per:

<details>
<summary><kbd>git grep -Pho "\binterface .*? {" | sort | uniq</kbd></summary>

```sh
interface Breach {
interface BreachResolution {
interface BreachResolutionRequest {
interface BreachRow {
interface BreachStats {
interface ComboBoxProps extends ComboBoxStateOptions<object> {
interface DataFileUrls {
interface EmailAddRequest {
interface EmailAddressRow {
interface EmailDeleteRequest {
interface EmailResendRequest {
interface EmailUpdateCommOptionRequest {
interface FeatureFlagRow {
interface FxaProfile {
interface GetLatestOnerepScanResult {
interface IntrinsicElements {
interface ItemObject {
interface JWT {
interface JwtPayload {
interface ListBoxProps extends AriaListBoxOptions<unknown> {
interface OnerepScanRow {
interface OnerepWebhookRequest {
interface OptionProps extends AriaListBoxOptions<unknown> {
interface PasswordChangeEvent {
interface PopoverProps extends AriaPopoverProps {
interface Profile {
interface ProfileChangeEvent {
interface ProgressBarProps extends AriaProgressBarProps {
interface Props extends ComponentProps<"button"> {
interface RelevantLocation {
interface RelevantLocationAlternate {
interface RequestBreachScanErrorResponse {
interface RequestBreachScanSuccessResponse {
interface ScanProgressBody {
interface SearchLocationParams {
interface SearchLocationResults {
interface Session {
interface Subscriber {
interface SubscriberBreachResolution {
interface SubscriberEmail {
interface SubscriberRow {
interface SubscriptionStateChangeEvent {
interface Tables {
interface UserInfo {
interface VerifiedEmail {
interface WelcomeScanBody {
interface Window {
```
</details>

2023-07-19 20:24 UTC, maxxcrawford approved these changes
LGTM

2023-07-19 21:37 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +            icon={<PhoneIcon alt="" width="13" height="13" />}
nit: I think we need a newer/different/better icon for IP Addresses than the PhoneIcon.

2023-07-19 21:41 UTC, rhelmer requested changes
Seeing a hydration error running locally, is there a script changing the DOM without React maybe?

2023-07-19 21:42 UTC, rhelmer commented on src/app/(proper_react)/redesign/(authenticated)/user/dashboard/page.tsx
> +  const profileId = result[0]["onerep_profile_id"] as number;
Hm not your fault, I'd like to clean up this function so it returns a nicer result...

2023-07-19 21:43 UTC, rhelmer reviewed
This looks great! I don't see any huge issues, just the hydration error when running in dev mode.

2023-07-19 21:45 UTC, rhelmer reviewed
BTW the error in Playwright is because it does a full build, here it is from the logs:

```
[WebServer] Failed to compile.

[WebServer] ./src/app/(proper_react)/redesign/(authenticated)/user/dashboard/Dashboard.stories.tsx:144:8
Type error: Property 'isUserScannedResults' is missing in type '{ user: { email: string; }; userBreaches: { emailVerifiedCount: number; emailTotalCount: number; emailSelectIndex: number; breachesData: { unverifiedEmails: never[]; verifiedEmails: { breaches: HibpLikeDbBreach[]; email: string; id: number; primary: true; verified: true; }[]; }; }; userScannedResults: ScanResult[]; ...' but required in type 'Props'.

  142 |   render: () => (
  143 |     <Shell l10n={getEnL10nSync()} session={null}>
> 144 |       <DashboardEl
      |        ^
  145 |         user={{ email: "example@example.com" }}
  146 |         userBreaches={{
  147 |           emailVerifiedCount: 0,
```

2023-07-19 23:49 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +  }
I'm a bit confused here... Aren't all the HIBP dataClasses already localized in https://github.com/mozilla/blurts-server/blob/main/locales/en/data-classes.ftl?

Assuming that's the file in question, I ran all the IDs and expected values against these computed values using the following trash code:
```js
import fs from "node:fs/promises";
import ini from "ini";

const dataClasses = await fs
  .readFile("./locales/en/data-classes.ftl", "utf-8")
  .then(ini.parse);

const diffs = Object.entries(dataClasses).reduce((acc, [key, expected]) => {
  const computed = formatOtherBreachCategoriesLabel(key).trim();
  if (computed !== expected) {
    acc[key] = { expected, computed };
  }
  return acc;
}, {});

console.log(JSON.stringify(diffs, null, 2));

function formatOtherBreachCategoriesLabel(sentence) {
  const words = sentence.split("-");
  const firstWord = words[0];
  const capitalizedFirstWord =
    firstWord.charAt(0).toUpperCase() + firstWord.slice(1);
  const restOfWords = words.slice(1).join(" ");
  return capitalizedFirstWord + " " + restOfWords;
}
```

<details>
<summary>RESULTS</summary>

```json
{
  "credit-card-cvv": {
    "expected": "Credit card CVV",
    "computed": "Credit card cvv"
  },
  "driver-s-licenses": {
    "expected": "Driver’s licenses",
    "computed": "Driver s licenses"
  },
  "family-members-names": {
    "expected": "Family members’ names",
    "computed": "Family members names"
  },
  "government-issued-ids": {
    "expected": "Government issued IDs",
    "computed": "Government issued ids"
  },
  "hiv-statuses": {
    "expected": "HIV statuses",
    "computed": "Hiv statuses"
  },
  "homepage-urls": {
    "expected": "Homepage URLs",
    "computed": "Homepage urls"
  },
  "imei-numbers": {
    "expected": "IMEI numbers",
    "computed": "Imei numbers"
  },
  "imsi-numbers": {
    "expected": "IMSI numbers",
    "computed": "Imsi numbers"
  },
  "ip-addresses": {
    "expected": "IP addresses",
    "computed": "Ip addresses"
  },
  "licence-plates": {
    "expected": "License Plates",
    "computed": "Licence plates"
  },
  "mac-addresses": {
    "expected": "MAC addresses",
    "computed": "Mac addresses"
  },
  "none-data-class": {
    "expected": "None",
    "computed": "None data class"
  },
  "other-data-class": {
    "expected": "Other",
    "computed": "Other data class"
  },
  "pins": {
    "expected": "PINs",
    "computed": "Pins"
  },
  "school-grades-class-levels": {
    "expected": "School grades (class levels)",
    "computed": "School grades class levels"
  },
  "sms-messages": {
    "expected": "SMS messages",
    "computed": "Sms messages"
  },
  "user-website-urls": {
    "expected": "User website URLs",
    "computed": "User website urls"
  },
  "vehicle-identification-numbers-vins": {
    "expected": "Vehicle identification numbers (VINs)",
    "computed": "Vehicle identification numbers vins"
  }
}
```
</details>

2023-07-19 23:55 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +}
Not sure if this is any clearer/better, but seemed to give the same results based on my limited testing:
```js
function formatOtherBreachCategoriesLabel(sentence) {
  return sentence
    .replaceAll("-", " ")
    .replace(/^[a-z]/, (i) => i.toUpperCase());
}
```

2023-07-20 04:37 UTC, merged

2023-07-20 15:27 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +}
@codemist Still curious what the method does, and why we need it.
Is it mainly for converting `DataClasses` slugs like "delivery-instructions" and "email-addresses" into "Delivery instructions" and "Email classes"?

All those should already be localized in https://github.com/mozilla/blurts-server/blob/main/locales/en/data-classes.ftl files.

2023-07-20 17:00 UTC, pdehaan commented on src/app/components/client/ExposureCard.tsx
> +  }
> although I'm not sure if we've encountered a breach with 5+ categories yet, may be an edge case

Here's a script that aggregates the number of dataclasses for each breach and dumps the results:
https://gist.github.com/pdehaan/17689268626dc4b247b6895264df0dc6