MNTOR-2742 - Implement Formstack iframe for cancellation survey
mozilla/blurts-server pull request #4409
Opened 2024-04-10 19:43 UTC by codemist

# References: 
Jira: MNTOR-2742
Figma: https://www.figma.com/file/DTbmXzCQCw2PxXpHQW8yfW/Monitor-MVP-Enhancements?type=design&node-id=424%3A11277&mode=design&t=jCoi4rrjYz2AT06M-1

# Screenshot (if applicable)

https://github.com/mozilla/blurts-server/assets/13066134/fab69f5d-cf2d-4dc6-96bc-75303874529d

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2024-04-10 23:58 UTC, pdehaan commented on locales-pending/settings-premium.ftl
> +settings-unsubscribe-dialog-confirmation-redirect-description-pt1 = We’ll automatically redirect you to your { -brand-mozilla } account where you can cancel your { -brand-monitor } subscription.
Q: should this be `{ -brand-mozilla} account` or `{ -brand-mozilla-account }`?

```sh
git grep -Pin "^-brand-mozilla(-account)?\s" locales/en locales-pending/ | cat

locales/en/app.ftl:14:-brand-Mozilla = Mozilla
locales/en/app.ftl:865:-brand-mozilla = Mozilla
locales/en/app.ftl:879:-brand-mozilla-account = Mozilla account
```

2024-04-10 23:58 UTC, pdehaan commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.module.scss
> +  transform: rotate(0.00001deg);
Interesting, what does the _almost_-rotation do?

2024-04-10 23:58 UTC, pdehaan commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
> +                      scrolling={"no"}
Any difference between `{"no"}` and `"no"`?

2024-04-10 23:58 UTC, pdehaan commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
> +                      title="Formstack Form"
Should this be localized?

2024-04-11 04:57 UTC, flodolo requested changes

2024-04-11 04:57 UTC, flodolo commented on locales-pending/settings-premium.ftl
> +settings-unsubscribe-dialog-confirmation-redirect-title = Directing you to your { -brand-mozilla } account to cancel
```suggestion
settings-unsubscribe-dialog-confirmation-redirect-title = Directing you to your { -brand-mozilla-account } to cancel
```

All the instances of `{ -brand-mozilla } account`  are mistakes that should be fixed over time.

2024-04-11 04:57 UTC, flodolo commented on locales-pending/settings-premium.ftl
> +settings-unsubscribe-dialog-confirmation-redirect-description-pt1 = We’ll automatically redirect you to your { -brand-mozilla } account where you can cancel your { -brand-monitor } subscription.
```suggestion
settings-unsubscribe-dialog-confirmation-redirect-description-pt1 = We’ll automatically redirect you to your { -brand-mozilla-account } where you can cancel your { -brand-monitor } subscription.
```

2024-04-11 04:57 UTC, flodolo commented on locales/en/settings.ftl
> +settings-unsubscribe-dialog-confirmation = Please note, all of your { -brand-monitor-plus } services will be <a { $faq_href }>permanently deleted</a> after your current billing cycle ends.
You need a new string ID to make this type of change.
https://mozilla-l10n.github.io/documentation/localization/making_string_changes.html

2024-04-11 13:00 UTC, Vinnl reviewed
Added some inline comments, but I'd like to see it with `main` as the target, just to make sure none of the cruft I added while spiking is still in there if it's no longer relevant :)

But: it looks great in the video! Much, much better than what I had before.

![image](https://github.com/mozilla/blurts-server/assets/4251/8a5a7f89-9a5a-44a8-bbcd-666120f9ca70)

2024-04-16 20:30 UTC, pdehaan commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/SettingsPage.test.tsx
> +it("takes you through the cancellation dialog flow all the way to sublat", async () => {
```suggestion
it("takes you through the cancellation dialog flow all the way to subplat", async () => {
```

2024-04-17 04:39 UTC, flodolo approved these changes

2024-04-17 19:52 UTC, Vinnl approved these changes
The top of the form gets cut off on small screens, but I'm not sure if that's a blocker.

![Screen Shot 2024-04-17 at 21 49 08](https://github.com/mozilla/blurts-server/assets/4251/b1412328-8d5e-4274-94dc-6602e398192b)

The unit tests look really good!

2024-04-17 19:52 UTC, Vinnl commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/View.tsx
> +                {/* changed string here */}
```suggestion
```

2024-04-18 16:08 UTC, merged