MNTOR-3161 - Add animation to Cancellation Flow
mozilla/blurts-server pull request #4540
Opened 2024-05-15 20:55 UTC by codemist

# References: 
Jira: MNTOR-3161
Figma: 

# Description

# Screenshot (if applicable)

Not applicable.

# How to test

# Checklist (Definition of Done)
- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2024-05-15 22:14 UTC, pdehaan commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
> +                  src="./animations/CancellationFlowAnimation.mp4"
Q: Should we put this on a/the CDN?

2024-05-17 12:20 UTC, Vinnl reviewed
The fallback image unfortunately doesn't work for me yet. I also uploaded a smaller version and a WebM version of the animation (ideally we get these directly from design, but I think this'll do).

Before merging, we probably also want to remove the larger version from the Git history (hat tip [to @maxxcrawford](https://mozilla.slack.com/archives/C054XAALP8C/p1715715262690789)). I can help with that, or alternatively, squashing while merging should do it too.

2024-05-17 12:20 UTC, Vinnl commented on src/app/(proper_react)/(redesign)/(authenticated)/user/(dashboard)/settings/CancelFlow.tsx
> +                />
I'm not seeing the fallback image if I disable animations... You'll probably need something like this: https://github.com/mozilla/fx-private-relay/blob/a515dc1c69e76a40c773c92d27af3ba485ea1e5e/frontend/src/components/layout/navigation/whatsnew/WhatsNewContent.module.scss#L32-L42

2024-05-17 12:20 UTC, Vinnl commented on public/animations/CancellationFlowAnimation.mp4
I noticed that this file was pretty big for a relatively static animation with few colours, at almost a Megabyte. For best quality it's probably best to export it directly from the source material, but I compressed this file myself and it doesn't seem too bad: https://github.com/mozilla/blurts-server/assets/4251/f05eea4b-d24e-4d40-b0a6-ac5f95390326

And while I was at it I also converted it to a VP9 WebM file which, again, would probably be better if done from the source material, but :shrug: https://github.com/mozilla/blurts-server/assets/4251/87d8c795-f341-4fcc-abc9-bbc3b23e8312

2024-05-21 11:49 UTC, flodolo approved these changes

2024-05-22 13:12 UTC, Vinnl commented on public/animations/CancellationFlowAnimation.mp4
Hmm OK, I'm a bit wary about some online tools since video parsers are common sources of vulnerabilities, so there's a small risk that the tool introduces security issues. Also, the original ~1MB `mp4` file is still present. I created https://github.com/mozilla/blurts-server/pull/4580 to replace the files with the smaller ones that I compressed with a trusted local tool, and that removes the old ones from the Git history.

2024-05-22 13:13 UTC, Vinnl requested changes
This is actually an approval, but to avoid the larger video files lingering around our Git history (slowing down repo cloning), I created https://github.com/mozilla/blurts-server/pull/4580. Feel free to merge that one - other than the video files it's the exact same as this PR.

2024-05-22 14:58 UTC, closed without merging