More detailed removal statuses (MNTOR-3201)
mozilla/blurts-server pull request #4686
Opened 2024-06-17 11:50 UTC by flozia

# References:

Jira: [MNTOR-3201](https://mozilla-hub.atlassian.net/browse/MNTOR-3201)
Figma: https://www.figma.com/design/DTbmXzCQCw2PxXpHQW8yfW/Monitor-MVP-Enhancements?node-id=1114-22017&t=0GjQ4xz52DTHHZxd-4

# Description

Updates the statuses on the exposure cards and the status explainer.

# How to test

1. The full list of statuses can be tested with a Plus user.
2. The limited breaches-only statuses can be tested with a user who is not eligible for Plus.

# Checklist (Definition of Done)

- [x] Localization strings have been added.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [x] I've added or updated the relevant sections in readme and/or code comments
- [x] I've added a unit test to test for potential regressions of this bug.
- [x] If this PR implements a feature flag or experimentation, the Ship Behind Feature Flag status in Jira has been set
- [x] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [x] All acceptance criteria are met.

2024-06-17 12:00 UTC, flodolo approved these changes

2024-06-17 17:40 UTC, jespy2 requested changes
Everything looks great!  There are discrepancies between the Figma specs and changes in this PR.  Please confirm the differences are result of outdated documentation

2024-06-17 17:40 UTC, jespy2 commented on src/app/components/client/exposure_card/ExposureCard.tsx
Header is missing "Your info for sale" on data breach cards per Figma specs.  I think this would only be appropriate for brokers(the text is present on those cards), but double checking.

2024-06-17 17:40 UTC, jespy2 commented on src/app/components/client/exposure_card/ExposureCard.tsx
Data breach fixed eligible for premium card not part of Figma.  Has "Data Breach" in header instead of "Your info for sale"

2024-06-17 17:40 UTC, jespy2 commented on src/app/components/client/ExposuresFilterExplainer.tsx
Modal for US and non-US users different from Figma specs.  Discussion with Florian clarified specs, but noting the difference here.

2024-06-17 18:43 UTC, flozia commented on src/app/components/client/exposure_card/ExposureCard.tsx
Good catch! This shows correctly in the current implementation and needs to be updated in Figma: [Left a comment over there](https://www.figma.com/design/DTbmXzCQCw2PxXpHQW8yfW?node-id=1114-36661#842570827).

2024-06-17 18:44 UTC, flozia commented on src/app/components/client/exposure_card/ExposureCard.tsx
This is the expected behavior. I left a comment in the previous comment mentioning the difference between the implementation and Figma: https://github.com/mozilla/blurts-server/pull/4686#discussion_r1643291364.

2024-06-17 18:44 UTC, flozia commented on src/app/components/client/exposure_card/ExposureCard.tsx
The buttons are being shown for “action needed” cards on the dashboard like here for example: https://deploy-preview-4686--fx-monitor-storybook.netlify.app/?path=/story/pages-logged-in-dashboard--dashboard-us-premium-unresolved-scan-unresolved-breaches.
<img width="1203" alt="image" src="https://github.com/mozilla/blurts-server/assets/13835474/a6a68425-92db-4708-ad25-0edc3f80b6d1">

2024-06-17 18:48 UTC, flozia commented on src/app/components/client/ExposuresFilterExplainer.tsx
The status labels that are being shown to US and non-US users depend on the condition [here](https://github.com/mozilla/blurts-server/pull/4686/files). Users who are eligible for Plus see more potential statuses as they have data brokers in their breach results, which come with more potential statuses than data breaches.

2024-06-17 19:01 UTC, jespy2 approved these changes
Thanks for the clarifications!

2024-06-17 19:13 UTC, merged

2024-06-18 07:11 UTC, flodolo commented on locales/en/dashboard.ftl
> +modal-exposure-indicator-action-needed = Advanced or manual action is needed by you to complete an action.
Sorry, realized this only when switching my brain to translator mode. "action needed to complete an action" doesn't make a lot of sense?