MNTOR-3465: HIBP responses with 429
mozilla/blurts-server pull request #4966
Opened 2024-08-21 01:37 UTC by mansaj

# References:

Jira: MNTOR-3465

# Description
Respond with 429 instead of 500 for HIBP webhook

# Checklist (Definition of Done)
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [x] All acceptance criteria are met.
- [x] Jira ticket has been updated (if needed) to match changes made during the development process.
- [x] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2024-08-21 17:47 UTC, rhelmer approved these changes

2024-08-21 17:47 UTC, rhelmer requested changes
We probably do want to be notified if the topic is not found, should that one report to Sentry or do you think `logger.error` is sufficient? That one is unlikely to fix itself

2024-08-21 22:57 UTC, mansaj commented
> We probably do want to be notified if the topic is not found, should that one report to Sentry or do you think `logger.error` is sufficient? That one is unlikely to fix itself

added sentry, it is much easier than combing through the logs at this point.
Do you think 429 or 500 make more sense here

2024-08-22 22:15 UTC, rhelmer approved these changes

2024-08-24 00:47 UTC, merged