Add landing page experiment
mozilla/blurts-server pull request #5434
Opened 2024-12-19 12:37 UTC by flozia

# References:

Jira: [MNTOR-3825](https://mozilla-hub.atlassian.net/browse/MNTOR-3825)

# Description

Adds the landing page experiment `landing-page-redesign`.

# Screenshot

TBD

# How to test

TBD

# Checklist (Definition of Done)

- [ ] Localization strings (if needed) have been added.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] I've added or updated the relevant sections in readme and/or code comments
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] If this PR implements a feature flag or experimentation, the Ship Behind Feature Flag status in Jira has been set
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.

2025-01-08 01:44 UTC, rhelmer requested changes
@flozia code changes look OK, I tried enabling locally and all I see is this on `/`. I noticed it's not passing tests too is this ready for review?
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/7fd9e8ef-3460-4ecb-a322-6ef3605e60fb" />

2025-01-08 01:44 UTC, rhelmer commented on config/nimbus.yaml
> +    description: Landing page redesign
I wonder if this might be confusing later, could we give it a more unique name? Do we ever remove these?

2025-01-08 09:34 UTC, flozia commented
> @flozia code changes look OK, I tried enabling locally and all I see is this on `/`. I noticed it's not passing tests too is this ready for review?

This PR is only adding the new landing page redesign page together with the `MobileShell` updates. The rest of the page is being implemented together with [MNTOR-3806](https://mozilla-hub.atlassian.net/browse/MNTOR-3806). It looks like the unit test failure is the same coverage issue we’ve experienced back in December — looking into it.

2025-01-08 15:17 UTC, rhelmer approved these changes

2025-01-09 16:14 UTC, flozia commented on src/app/(proper_react)/(redesign)/(public)/page.tsx
> +      )}
One is the new `LandingViewRedesign` layout and the other is the current `LandingView` — both are taking the same props.

2025-01-09 20:00 UTC, merged